name: "Test"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: "RUN SCAN"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: owasp/zap2docker-stable
        target: http://testhtml5.vulnweb.com

#     - name: OWASP ZAP Baseline Scan
#           # You may pin to the exact commit or the version.
#           # uses: zaproxy/action-baseline@acd8e997263688cb49cb5ff8247a4b2758c548ab
#       run: docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://testhtml5.vulnweb.com -g gen.conf -J test_report.json
#       # run: docker run -t owasp/zap2docker-stable zap-baseline.py -t http://testhtml5.vulnweb.com
